### ISSUE TITLE
support display of other constraints

### ISSUE THREAD

**Issue by ainthek** [gratex/schema2doc#1]
see 

print constraints, only intervals are now supported (TODO)

**Comment by pmelisko** [comment]
Added support for limit contraints (minimum, minLenght, minItems and corresponding maxims) with argument -a, added by: 5fa7f104a51270a49eb41bd723d5eb114952970c

sample:

```
$ echo '{"name": {"type": "string","minLength":10}}' | schema2doc -a
RQ/NN   Field   Type    Format  Constraints     Desc
------  ------  ------  ------  ------  ------
-+      name    string          <10,*>
```
